# Generated by Django 4.2.27 on 2026-02-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('it', 'TI'), ('hr', 'RH'), ('finance', 'Financeiro'), ('general', 'Geral')], default='general', max_length=20),
        ),
    ]
